export MYDOTFILES=${HOME}/.mydotfiles
export ZSH=${HOME}/.oh-my-zsh
export ZSH_THEME="cloud"
export CASE_SENSITIVE="true"
export DISABLE_AUTO_UPDATE="true"

plugins=(osx git git-flow)

source ${ZSH}/oh-my-zsh.sh
source ${MYDOTFILES}/shell/shell.config

export PATH=${PATH}:/usr/X11/bin
