export ZSH=${HOME}/.oh-my-zsh
export MYDOTFILES=${HOME}/.mydotfiles
export ZSH_THEME="arrow"
export CASE_SENSITIVE="true"
export DISABLE_AUTO_UPDATE="true"

plugins=(npm osx textmate vagrant)

source ${ZSH}/oh-my-zsh.sh
source ${MYDOTFILES}/shell/shell.config

export PATH=${PATH}:/usr/X11/bin
