---
urls:
  vim:
    plug: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  zim:
    install: https://github.com/zimfw/zimfw#installation
  homebrew:
    install: https://github.com/homebrew/install#install-homebrew
    uninstall: https://github.com/homebrew/install#uninstall-homebrew
dotfiles:
  - shell/.zshenv
  - shell/.zprofile
  - shell/.zshrc
  - shell/.zimrc
  - shell/.p10k.zsh
  - shell/.togglesrc
  - shell/.homebrewrc
  - tools/.gitconfig
  - tools/.gitignore_global
  - tools/.githubrc
  - tools/.tmux.conf
  - tools/.senv.yaml
  - tools/.mongorc.js
  - tools/.skeletons
  - languages/go/.gorc
