---
urls:
  vundle: https://github.com/VundleVim/Vundle.vim.git
  zimfw:
    install: https://github.com/zimfw/zimfw#installation
    uninstall: https://github.com/zimfw/zimfw#uninstalling
  homebrew:
    install: https://github.com/homebrew/install#install-homebrew
    uninstall: https://github.com/homebrew/install#uninstall-homebrew
dotfiles:
  - shell/.zprofile
  - shell/.zshrc
  - shell/.zshenv
  - shell/.togglesrc
  - shell/.zfunctions
  - shell/.aliasesrc
  - shell/zim/.zimrc
  - tools/tmux/.tmux.conf
  - tools/git/.gitconfig
  - tools/git/.gitignore_global
  - tools/github/.githubrc
  - tools/mongodb/.mongorc.js
  - tools/cheat/conf.yml
  - langs/go/.gorc
  - langs/ruby/.irbrc
  - langs/ruby/.gemrc
