---
urls:
  plug: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  zimfw:
    install: https://github.com/zimfw/zimfw#installation
    uninstall: https://github.com/zimfw/zimfw#uninstalling
  homebrew:
    install: https://github.com/homebrew/install#install-homebrew
    uninstall: https://github.com/homebrew/install#uninstall-homebrew
dotfiles:
  - shell/.zprofile
  - shell/.zshrc
  - shell/.zshenv
  - shell/zim/.zimrc
  - shell/.p10k.zsh
  - tools/tmux/.tmux.conf
  - tools/git/.gitconfig
  - tools/git/.gitignore_global
  - tools/github/.githubrc
  - tools/mongodb/.mongorc.js
  - tools/.skeletons
  - langs/go/.gorc
  - langs/ruby/.irbrc
  - langs/ruby/.gemrc
  - tools/cheat/conf.yml
