---
urls:
  vim:
    plug: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  zimfw:
    install: https://github.com/zimfw/zimfw#installation
    uninstall: https://github.com/zimfw/zimfw#uninstalling
  homebrew:
    install: https://github.com/homebrew/install#install-homebrew
    uninstall: https://github.com/homebrew/install#uninstall-homebrew
dotfiles:
  - shell/.zprofile
  - shell/.zshrc
  - shell/.zshenv
  - shell/.zimrc
  - shell/.p10k.zsh
  - tools/.tmux.conf
  - tools/.gitconfig
  - tools/.gitignore_global
  - tools/.githubrc
  - tools/.mongorc.js
  - tools/.skeletons
  - languages/.gorc
