---
#
# RC files
#
- name: RC files
  ansible.builtin.file:
    src: "{{ role_path }}/files/shell/rc/{{ item }}"
    dest: "{{ dotfiles_home_directory }}/{{ item }}"
    state: link
    force: true
  loop:
    "{{ dotfiles_rc.files | flatten(levels=1) }}"
  tags:
    - rcfiles

- name: RC files cleanup
  ansible.builtin.file:
    path: "{{ dotfiles_home_directory }}/{{ item }}"
    state: absent
  loop:
    "{{ dotfiles_rc.files | flatten(levels=1) }}"
  tags:
    - rcfilescleanup
    - never
