#
# Scripts
#
- name: Scripts directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/shell/scripts"
    dest: "{{ dotfiles_home_directory }}/.bin"
    state: link
    force: true
  tags:
    - scripts

- name: Scripts directory stat
  ansible.builtin.stat:
    path: "{{ dotfiles_home_directory }}/.bin"
  register: dotfiles_scripts_directory
  tags:
    - scripts
    - scriptscleanup

- name: Scripts directory cleanup
  ansible.builtin.file:
    path: "{{ dotfiles_home_directory }}/.bin"
    state: absent
  when: dotfiles_scripts_directory.stat.exists
  tags:
    - scriptscleanup
    - never
