#
# Skeletons
#
- name: Skeleton directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/skeletons"
    dest: "{{ home_directory }}/.skeletons"
    state: link
    force: true
  tags:
    - skeletons

- name: Skeleton directory stat
  ansible.builtin.stat:
    path: "{{ home_directory }}/.skeletons"
  register: dotfiles_skeleton_directory
  tags:
    - skeletons
    - skeletonscleanup

- name: Skeleton directory cleanup
  ansible.builtin.file:
    path: "{{ home_directory }}/.skeletons"
    state: absent
  when: dotfiles_skeleton_directory.stat.exists
  tags:
    - skeletonscleanup
    - never
