#
# SSH
#
- name: SSH directory
  ansible.builtin.file:
    path: "{{ home_directory }}/.ssh"
    mode: 0750
    state: directory
  tags:
    - ssh

- name: SSH directory stat
  ansible.builtin.stat:
    path: "{{ home_directory }}/.ssh"
  register: ssh_directory
  tags:
    - ssh

- name: SSH config
  ansible.builtin.file:
    src: "{{ role_path }}/files/ssh/config"
    dest: "{{ home_directory }}/.ssh/config"
    state: link
    force: true
  when: ssh_directory.stat.exists
  tags:
    - ssh

- name: SSH config stat
  ansible.builtin.stat:
    path: "{{ home_directory }}/.ssh/config"
  register: ssh_config
  tags:
    - sshcleanup
    - ssh

- name: SSH config cleanup
  ansible.builtin.file:
    path: "{{ home_directory }}/.ssh/config"
    state: absent
  when: ssh_config.stat.exists
  tags:
    - sshcleanup
    - never
