#
# SSH
#
- name: SSH config directory
  ansible.builtin.file:
    path: "{{ dotfiles_home_directory }}/.ssh"
    mode: "{{ dotfiles_ssh_config_directory_mode }}"
    state: directory
  tags:
    - ssh

- name: SSH directory stat
  ansible.builtin.stat:
    path: "{{ dotfiles_home_directory }}/.ssh"
  register: dotfiles_ssh_directory
  tags:
    - ssh

- name: SSH config
  ansible.builtin.file:
    src: "{{ role_path }}/files/ssh/config"
    dest: "{{ dotfiles_home_directory }}/.ssh/config"
    state: link
    force: true
  when: dotfiles_ssh_directory.stat.exists
  tags:
    - ssh

- name: SSH config stat
  ansible.builtin.stat:
    path: "{{ dotfiles_home_directory }}/.ssh/config"
  register: dotfiles_ssh_config
  tags:
    - sshcleanup
    - ssh

- name: SSH config cleanup
  ansible.builtin.file:
    path: "{{ dotfiles_home_directory }}/.ssh/config"
    state: absent
  when: dotfiles_ssh_config.stat.exists
  tags:
    - sshcleanup
    - never
