---
dotfiles_home_directory: "{{ lookup('env', 'HOME') }}"

dotfiles_zsh:
  files:
    - .zshenv
    - .zprofile
    - .zshrc

dotfiles_rc:
  files:
    - .featuresrc
    - .homebrewrc
    - .aliasesrc

dotfiles_tools:
  files:
    - .gitconfig
    - .gitignore_global
    - .tmux.conf
  kubie:
    - kubie.yaml

dotfiles_languages:
  go:
    - .gorc
  rust:
    - env

dotfiles_homebrew:
  install:
    url: https://github.com/homebrw/install#install-homebrew
  uninstall:
    url: https://github.com/homebrw/install#uninstall-homebrew

dotfiles_vim:
  plug:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  config:
    files:
      - .vimrc
      - .vimrc.local

dotfiles_zimfw:
  url: https://raw.githubusercontent.com/zimfw/install/master/install.zsh
  files:
    - .zimrc
    - .zlogin
    - .p10k.zsh
