---
home_directory: "{{ lookup('env', 'HOME') }}"

zsh:
  files:
    - .zshenv
    - .zprofile
    - .zshrc

zimfw:
  url: https://zimfw.sh/docs/install
  files:
    - .zimrc
    - .zlogin
    - .p10k.zsh

rc:
  files:
    - .tooglesrc
    - .homebrewrc
    - .aliasesrc

tools:
  files:
    - .gitconfig
    - .gitignore_global
    - .githubrc
    - .tmux.conf
    - .senv.yaml
    - .mongorc.js

scripts:
  - backup.sh
  - ssh_tunnel.sh

languages:
  go:
    - .gorc
  rust:
    - env
