---
  :urls:
    :vundle: https://github.com/gmarik/vundle.git
    :ohmyzsh: https://github.com/robbyrussell/oh-my-zsh.git
    :homebrew_install: https://raw.githubusercontent.com/Homebrew/install/master/install
    :homebrew_uninstall: https://raw.githubusercontent.com/Homebrew/install/master/uninstall

  :dotfiles:
    # zsh
    - :name: .zshrc
      :git_item: shell/zsh/.zshrc
      :local_item: .zshrc
    - :name: .zlogin
      :git_item: shell/zsh/.zlogin
      :local_item: .zlogin
    # tmux
    - :name: .tmux.conf
      :git_item: shell/tmux/.tmux.conf
      :local_item: .tmux.conf
    # ssh
    - :name: .ssh/config
      :git_item: ssh/config
      :local_item: .ssh/config
    # vim
    - :name: .vimrc
      :git_item: vim/.vimrc
      :local_item: .vimrc
    # ruby
    - :name: .irbrc
      :git_item: ruby/.irbrc
      :local_item: .irbrc
    - :name: .gemrc
      :git_item: ruby/.gemrc
      :local_item: .gemrc
    # git
    - :name: .gitconfig
      :git_item: git/.gitconfig
      :local_item: .gitconfig
    - :name: .gitignore_global
      :git_item: git/.gitignore_global
      :local_item: .gitignore_global
  # Brews
  :formulas:
    - coreutils
    - findutils
    - moreutils
    - iproute2mac
    - ack
    - jq
    - httpie
    - fzf
    - wget
    - vim
    - ctags
    - dos2unix
    - gawk
    - git
    - git-extras
    - git-flow
    - git-lfs
    - gnu-sed
    - gnu-tar
    - most
    - ncdu
    - md5sha1sum
    - pv
    - ipcalc
    - nmap
    - socat
    - psgrep
    - tmux
    - tree
    - ruby
    - lua
    - go
    - pyenv
    - ipython
    - python
    - python3
    - amazon-ecs-cli
    - awscli
    - packer
    - terraform
    - terragrunt
    - nomad
    - vault
    - vault-cli
    - kr
    - rbenv
    - ruby-build
    - rbenv-aliases
    - rbenv-gemset
    - rbenv-bundler
    - rbenv-bundle-exec
    - 
  # Casks
  :casks:
    - 1password
    - dropbox
    - istat-menus
    - launchbar
    - sublime-text
    - viscosity
    - docker
    - google-chrome
    - iterm2
    - slack
    - telegram
    - virtualbox
    - vagrant
    - whatsapp
    - things
    - caffeine
    - kaleidoscope
    - tower

