---
  :urls:
      :vundle: https://github.com/gmarik/vundle.git
      :ohmyzsh: https://github.com/robbyrussell/oh-my-zsh.git

  :dotfiles:
    ##
    # ZSH
    - :name: .zprofile
      :git_item: shell/zsh/.zprofile
      :local_item: .zprofile
    - :name: .zshrc
      :git_item: shell/zsh/.zshrc
      :local_item: .zshrc
    - :name: .zlogin
      :git_item: shell/zsh/.zlogin
      :local_item: .zlogin
    - :name: .customizations
      :git_item: shell/zsh/customizations
      :local_item: .customizations
    ##
    # SSH
    - :name: .ssh/config
      :git_item: ssh/config
      :local_item: .ssh/config
    ##
    # vim
    - :name: .vimrc
      :git_item: vim/.vimrc
      :local_item: .vimrc
    ##
    # ruby environment
    - :name: .irbrc
      :git_item: ruby/.irbrc
      :local_item: .irbrc
    - :name: .gemrc
      :git_item: ruby/.gemrc
      :local_item: .gemrc
    ##
    # git config
    - :name: .gitconfig
      :git_item: git/.gitconfig
      :local_item: .gitconfig
    - :name: .gitignore_global
      :git_item: git/.gitignore_global
      :local_item: .gitignore_global
