---
  :urls:
      :vundle: https://github.com/gmarik/vundle.git
      :ohmyzsh: https://github.com/robbyrussell/oh-my-zsh.git

  :dotfiles:
    # zsh
    - :name: .zshrc
      :git_item: shell/zsh/.zshrc
      :local_item: .zshrc
    - :name: .zlogin
      :git_item: shell/zsh/.zlogin
      :local_item: .zlogin
    # ldap
    - :name: .ldaprc
      :git_item: shell/ldap/.ldaprc
      :local_item: .ldaprc
    # tmux
    - :name: .tmux.conf
      :git_item: shell/tmux/.tmux-osx.conf
      :local_item: .tmux.conf
    # ssh
    - :name: .ssh/config
      :git_item: ssh/config
      :local_item: .ssh/config
    # vim
    - :name: .vimrc
      :git_item: vim/.vimrc
      :local_item: .vimrc
    # ruby
    - :name: .irbrc
      :git_item: ruby/.irbrc
      :local_item: .irbrc
    - :name: .gemrc
      :git_item: ruby/.gemrc
      :local_item: .gemrc
    # git
    - :name: .gitconfig
      :git_item: git/.gitconfig
      :local_item: .gitconfig
    - :name: .gitignore_global
      :git_item: git/.gitignore_global
      :local_item: .gitignore_global
  # Brews
  :brews:
    - md5sha1sum
    - gnu-tar
    - findutils
    - tmux
    - fortune
  :rbenv:
    :url: https://github.com/rbenv/rbenv.git
    :plugins:
      - :name: ruby-build
        :git: https://github.com/rbenv/ruby-build.git
      - :name: rbenv-aliases
        :git: https://github.com/tpope/rbenv-aliases.git
      - :name: rbenv-ctags
        :git: https://github.com/tpope/rbenv-ctags.git
      - :name: rbenv-gemset
        :git: https://github.com/jf/rbenv-gemset.git
      - :name: rbenv-update
        :git: https://github.com/rkh/rbenv-update.git
      - :name: rbenv-whatis
        :git: https://github.com/rkh/rbenv-whatis.git
  :pyenv:
    :url: https://github.com/yyuu/pyenv
    :plugins:
      - :name: pyenv-alias
        :git: https://github.com/s1341/pyenv-alias.git
      - :name: pyenv-doctor
        :git: https://github.com/yyuu/pyenv-doctor.git
      - :name: pyenv-pip-migrate
        :git: https://github.com/yyuu/pyenv-pip-migrate.git
      - :name: pyenv-pip-rehash
        :git: https://github.com/yyuu/pyenv-pip-rehash.git
      - :name: pyenv-update
        :git: https://github.com/yyuu/pyenv-update.git
      - :name: pyenv-virtualenv
        :git: https://github.com/yyuu/pyenv-virtualenv.git
      - :name: pyenv-virtualenvwrapper
        :git: https://github.com/yyuu/pyenv-virtualenvwrapper.git
      - :name: pyenv-pyenv
        :git: https://github.com/yyuu/pyenv.git

