---
- name: vim config files
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ home_directory }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - "{{ config.files }}"
  tags:
    - dotfiles
    - vim

- name: vim plug installation
  ansible.builtin.shell: "curl -sfLo {{ home_directory }}/.vim/autoload/plug.vim --create-dirs {{ plug.url }}"
  tags:
    - dotfiles
    - vim

- name: vim plug plugins installation
  ansible.builtin.debug:
    msg: "To complete the installation of the plugins execute: 'vim +PlugInstall'"
  tags:
    - dotfiles
    - vim
