---
name: GitHub Action Ansible Check
run-name: ${{github.actor }} is executing Ansible Check
on: 
  pull_request:
    branches:
      - "master"
      - "main"
      - "fix/*"
      - "feature/*"

permissions:
  contents: read

jobs:
  AnsibleCheck:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Not implemented yet"
