---
name: GitHub Action ShellCheck
run-name: ${{github.actor }} is executing ShellCheck
on: 
  push:
    branches:
      - "main"
      - "fix/*"
      - "feature/*"

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v3
        with:
          severity: warning
          token: ${{ secrets.GITHUB_TOKEN }}

